apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default
data:
  config.json: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpHRnVhV1ZzZW5WbWNtazZXbmwyU2lVbFJuWkFKRFIwWm5RcCIKCQl9Cgl9Cn0=